/// Base class for all chat stream events (Token, Done, Error).
///
/// This class represents events emitted during Server-Sent Events (SSE)
/// streaming from the backend chat endpoint.
///
/// Event Types:
/// - [TokenEvent]: Individual tokens generated by the LLM
/// - [DoneEvent]: Stream completion with full response and metadata
/// - [ErrorEvent]: Stream errors with retry information
abstract class ChatStreamEvent {
  const ChatStreamEvent();
}

/// Token event representing a single LLM-generated token.
///
/// Emitted during streaming as the LLM generates text incrementally.
///
/// Example:
/// ```dart
/// final tokenEvent = TokenEvent(token: "Hello", isFinal: false);
/// print(tokenEvent.token); // "Hello"
/// ```
class TokenEvent extends ChatStreamEvent {
  const TokenEvent({required this.token, this.isFinal = false});

  /// Create TokenEvent from SSE JSON data payload.
  ///
  /// Expected format:
  /// ```json
  /// {"token": "Hello", "is_final": false}
  /// ```
  factory TokenEvent.fromJson(Map<String, dynamic> json) => TokenEvent(
    token: json['token'] as String,
    isFinal: json['is_final'] as bool? ?? false,
  );

  /// The generated text token (can be word fragment, word, or punctuation).
  final String token;

  /// Whether this is the final token in the stream.
  final bool isFinal;

  @override
  String toString() => 'TokenEvent(token: $token, isFinal: $isFinal)';

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TokenEvent &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          isFinal == other.isFinal;

  @override
  int get hashCode => token.hashCode ^ isFinal.hashCode;
}

/// Done event signaling end of stream with full response and metadata.
///
/// Emitted once when the LLM completes generating the response.
/// Contains the complete response text, sources used, and generation metadata.
///
/// Example:
/// ```dart
/// final doneEvent = DoneEvent(
///   fullResponse: "The sky is blue due to Rayleigh scattering.",
///   sources: ["physics_textbook.pdf"],
///   metadata: {"token_count": 42, "template_used": "TECHNICAL"},
/// );
/// ```
class DoneEvent extends ChatStreamEvent {
  const DoneEvent({
    required this.fullResponse,
    this.sources = const [],
    this.metadata = const {},
  });

  /// Create DoneEvent from SSE JSON data payload.
  ///
  /// Expected format:
  /// ```json
  /// {
  ///   "full_response": "Complete text...",
  ///   "sources": ["doc1.md", "doc2.md"],
  ///   "metadata": {"token_count": 42, "template_used": "TECHNICAL"}
  /// }
  /// ```
  factory DoneEvent.fromJson(Map<String, dynamic> json) => DoneEvent(
    fullResponse: json['full_response'] as String,
    sources:
        (json['sources'] as List<dynamic>?)?.map((e) => e as String).toList() ??
        [],
    metadata: json['metadata'] as Map<String, dynamic>? ?? {},
  );

  /// Complete generated response (concatenation of all tokens).
  final String fullResponse;

  /// List of document sources referenced during generation.
  final List<String> sources;

  /// Generation metadata (token count, template used, etc.).
  final Map<String, dynamic> metadata;

  @override
  String toString() {
    final preview = fullResponse.length > 50
        ? '${fullResponse.substring(0, 50)}...'
        : fullResponse;
    return 'DoneEvent(fullResponse: $preview, sources: $sources)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DoneEvent &&
          runtimeType == other.runtimeType &&
          fullResponse == other.fullResponse &&
          _listEquals(sources, other.sources);

  @override
  int get hashCode => fullResponse.hashCode ^ sources.hashCode;

  /// Helper for list equality comparison.
  bool _listEquals<T>(List<T>? a, List<T>? b) {
    if (a == null) {
      return b == null;
    }
    if (b == null || a.length != b.length) {
      return false;
    }
    for (final index in List.generate(a.length, (i) => i)) {
      if (a[index] != b[index]) {
        return false;
      }
    }
    return true;
  }
}

/// Error event representing a stream error.
///
/// Emitted when an error occurs during streaming (connection issues,
/// LLM failures, backend errors).
///
/// Example:
/// ```dart
/// final errorEvent = ErrorEvent(
///   error: "Connection timeout",
///   code: "TIMEOUT_ERROR",
///   shouldRetry: true,
/// );
/// if (errorEvent.shouldRetry) {
///   // Implement retry logic
/// }
/// ```
class ErrorEvent extends ChatStreamEvent {
  const ErrorEvent({
    required this.error,
    required this.code,
    this.shouldRetry = false,
  });

  /// Create ErrorEvent from SSE JSON data payload.
  ///
  /// Expected format:
  /// ```json
  /// {
  ///   "error": "Connection failed",
  ///   "code": "CONNECTION_ERROR",
  ///   "retry": true
  /// }
  /// ```
  factory ErrorEvent.fromJson(Map<String, dynamic> json) => ErrorEvent(
    error: json['error'] as String,
    code: json['code'] as String,
    shouldRetry: json['retry'] as bool? ?? false,
  );

  /// Human-readable error message.
  final String error;

  /// Error code for programmatic handling (e.g., "CONNECTION_ERROR").
  final String code;

  /// Whether client should retry the request.
  final bool shouldRetry;

  @override
  String toString() =>
      'ErrorEvent(error: $error, code: $code, shouldRetry: $shouldRetry)';

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ErrorEvent &&
          runtimeType == other.runtimeType &&
          error == other.error &&
          code == other.code &&
          shouldRetry == other.shouldRetry;

  @override
  int get hashCode => error.hashCode ^ code.hashCode ^ shouldRetry.hashCode;
}
