import '../../../../domain/entities/chat_stream_event.dart';
import '../entities/chat_message.dart';
import '../entities/document_proposal.dart';

/// Repository interface for chat operations.
abstract class ChatRepository {
  /// Generates document content using RAG + LLM with SSE streaming.
  ///
  /// Returns a stream of tokens that together form the complete document.
  Stream<String> generateDocument(
    String docType,
    String userInput,
    Map<String, dynamic> context,
  );

  /// Send message and get streaming response (NEW - HU-4.3).
  ///
  /// Returns stream of [ChatStreamEvent] as tokens are generated by the LLM.
  ///
  /// Example:
  /// ```dart
  /// await for (final event in repository.sendMessageStream(
  ///     message, projectId)) {
  ///   if (event is TokenEvent) {
  ///     // Append token to UI progressively
  ///   } else if (event is DoneEvent) {
  ///     // Mark message complete, show sources/metadata
  ///   } else if (event is ErrorEvent) {
  ///     // Handle error, retry if shouldRetry==true
  ///   }
  /// }
  /// ```
  Stream<ChatStreamEvent> sendMessageStream(
    String message,
    String projectId, {
    String? docType, // 👈 EL METADATA VITAL PARA LA MÁQUINA DE ESTADOS
    String? userName,
  });

  /// Saves a document proposal to persistent storage.
  Future<void> saveProposal(DocumentProposal proposal);

  /// Retrieves chat history from storage.
  Future<List<ChatMessage>> getChatHistory(String projectId);

  /// Saves a single message to chat history.
  Future<void> saveMessage(String projectId, ChatMessage message);

  /// Clears chat history for a project.
  Future<void> clearChatHistory(String projectId);
}
